title: ED-TTS Multi-Scale Emotion Modeling using Cross-Domain Emotion Diarization for Emotional Speech Synthesis
description: Submitted to ICASSP 2024


theme: jekyll-theme-cayman

github:
  repository_url: https://github.com/hexastrayer/
